# application.yml
# Spring Boot, MyBatis, 데이터소스 설정 파일
# @author : jihye
# @fileName : application.yml
# @since : 250708
# @history
#   - 250708 | jihye | 초기 환경 설정 작성
#   - 250711 | yukyeong | username: ecovery로 수정, map-underscore-to-camel-case 설정 추가

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecovery?serverTimezone=UTC
    username: ecovery
    password: 1234
  # Live Reload 기능 활성화
  devtools:
    livereload:
      enabled: true

  # Thymeleaf cache 사용 중지
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ # Thymeleaf 템플릿 파일이 있는 기본 경로 설정
    suffix: .html # Thymeleaf 템플릿 파일의 확장자 설정

  servlet:
    multipart:
      max-File-Size: 20MB # 파일 한 개당 최대 사이즈
      max-request-size: 100MB # 요청당 최대 파일 크기

# 상품 이미지 업로드 경로
#itemImgLocation: C:/shop/item

# 리소스 이미지 업로드 경로
#uploadPath: file:///C:/shop/


mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

  # DB 컬럼명과 Java 필드명 자동 매핑 (snake_case → camelCase)
  configuration:
    map-underscore-to-camel-case: true

# 쿼리에 물음표로 출력되는 바인드 파라미터 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace